repository_type: pipeline
lint:
  files_exist:
    - assets/multiqc_config.yml
    - assets/nf-core-curationpretext_logo_light.png
    - docs/images/nf-core-curationpretext_logo_light.png
    - docs/images/nf-core-curationpretext_logo_dark.png
  files_unchanged:
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - LICENSE
    - .github/CONTRIBUTING.md
    - docs/README.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
