lint:
  files_exist:
    - assets/multiqc_config.yml
    - assets/nf-core-curationpretext_logo_light.png
    - docs/images/nf-core-curationpretext_logo_light.png
    - docs/images/nf-core-curationpretext_logo_dark.png
  multiqc_config:
    - assets/multiqc_config.yml
  files_unchanged:
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - LICENSE
    - .github/CONTRIBUTING.md
    - docs/README.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - assets/email_template.txt
    - assets/email_template.html
    - assets/sendmail_template.txt
    - .prettierignore
    - assets/email_template.txt
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Damon-Lee B Pointon (@DLBPointon)
  description: A simple pipeline to generate pretext files for genomic curation.
  force: false
  is_nfcore: true
  name: curationpretext
  org: nf-core
  outdir: .
  version: 1.2.0
